//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Graph_Manager {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Graph_Manager.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\Images\\AddSelected.png.
        /// </summary>
        public static string AddSelected {
            get {
                return ResourceManager.GetString("AddSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\Images\\AddUnselected.png.
        /// </summary>
        public static string AddUnselected {
            get {
                return ResourceManager.GetString("AddUnselected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\Images\\CircleBlue.png.
        /// </summary>
        public static string CircleBlue {
            get {
                return ResourceManager.GetString("CircleBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\Images\\CircleOrange.png.
        /// </summary>
        public static string CircleOrange {
            get {
                return ResourceManager.GetString("CircleOrange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\Images\\DeleteSelected.png.
        /// </summary>
        public static string DeleteSelected {
            get {
                return ResourceManager.GetString("DeleteSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\Images\\DeleteUnselected.png.
        /// </summary>
        public static string DeleteUnselected {
            get {
                return ResourceManager.GetString("DeleteUnselected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\Images\\DragSelected.png.
        /// </summary>
        public static string DragSelected {
            get {
                return ResourceManager.GetString("DragSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\Images\\DragUnselected.png.
        /// </summary>
        public static string DragUnselected {
            get {
                return ResourceManager.GetString("DragUnselected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30.
        /// </summary>
        public static string ImageHeight {
            get {
                return ResourceManager.GetString("ImageHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30.
        /// </summary>
        public static string ImageWidth {
            get {
                return ResourceManager.GetString("ImageWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15.
        /// </summary>
        public static string Radius {
            get {
                return ResourceManager.GetString("Radius", resourceCulture);
            }
        }
    }
}
